@startuml
start
:Arraylist<> inputs;

 while (i < 5 ?)
    :Sout("Enter a number: ");
    :getInput(Scanner(), inputs);
    :i++;
 endwhile(no)

 while (i < 5 ?)
    :int sum += (i+1);
 endwhile(no)

 :Sout(sum);
end
@enduml